version: "3.3"

services:
  monolith-next:
    container_name: monolith-next
    restart: always
    image: node:20.19.5
    ports:
      - 4000:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/monolith-next
    working_dir: /usr/src/monolith-next

    networks:
      - client-network

    command: sh -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
